### ISSUE TITLE
Since version 0.10.0 pure wildcard does not work in some cases

### ISSUE THREAD

**Issue by bzakdd** [cpburnz/python-pathspec#62] opened 2022-09-01 09:10 UTC
Behavior of pattern "match everything" changed when upgrading from version 0.9.0 to 0.10.0:

---
Version 0.9.0
```python
>>> import pathspec
>>> patterns = pathspec.PathSpec.from_lines(pathspec.patterns.GitWildMatchPattern, ["*"])
>>> 
>>> print(patterns.match_file('anydir/file.txt'))
True
```
Result is as expected

---
Version 0.10.0
```python
>>> import pathspec
>>> patterns = pathspec.PathSpec.from_lines(pathspec.patterns.GitWildMatchPattern, ["*"])
>>> 
>>> print(patterns.match_file('anydir/file.txt'))
False
```
Result is wrong. `*` should match any file, but it doesn't match `anydir/file.txt`.

---

Discovered when checking case "match everything except for one directory":
```python
patterns = pathspec.PathSpec.from_lines(pathspec.patterns.GitWildMatchPattern, ["*", "!product_dir/"])
```
On version 0.9.0 it correctly matches file outside of `product_dir` and doesn't match file inside:
```python
>>> print(patterns.match_file('anydir/file.txt'))
True
>>> print(patterns.match_file('product_dir/file.txt'))
False
```
On version 0.10.0 it doesn't match in either case:
```python
>>> print(patterns.match_file('anydir/file.txt'))
False
>>> print(patterns.match_file('product_dir/file.txt'))
False
```

**Comment by cpburnz** [comment] 2022-09-02 12:52
Hi @bzakdd, thanks for the bug report. This was a regression from fixing #19. This is now fixed and will be in the v0.10.1 release.

**Closed by cpburnz** 2022-09-02 12:52 UTC

**Comment by bzakdd** [comment] 2022-09-02 13:32
@cpburnz Thank you!)

**Comment by ichard26** [comment] 2022-09-05 03:09
Hi @cpburnz, looks like this has the potential to cause some serious usability problems for downstream users. Black just received a bug report (https://github.com/psf/black/issues/3256) where Black is now reformatting virtual environments (!) named `env` with `pathspec==10.0.0`. This is because virtual environments (only those created by `virtualenv`, not `venv`) contain a `.gitignore` file that simply excludes everything. 

```console
$ virtualenv env
created virtual environment CPython3.8.5.final.0-64 in 2959ms
  creator CPython3Posix(dest=/home/ichard26/programming/oss/dir/env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/ichard26/.local/share/virtualenv)
    added seed packages: pip==22.2.2, setuptools==63.4.3, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

$ cat env/.gitignore 
# created by virtualenv automatically
*
```

Black doesn't have `env` as part of its default excludes so our safeguard that usually prevents virtual environments from being reformatted is useless here. I know that naming virtual environments `env` isn't particularly common, but when it does happen, this issue can make Black unusable (since virtual environments can often have an insane amount of code to reformat). Yes it's easy to fix (put `env` in your `--extend-exclude` configuration), but it's better if this isn't necessary in the first place. 

Would you be open to yanking pathspec 0.10.0 on PyPI? It will prevent most users from getting the broken version, but won't break people who are already locked on 0.10.0. It's a bit like a "strongly discouraged for use" marker but for pip :slightly_smiling_face: [This post explains it well](https://snarky.ca/what-to-do-when-you-botch-a-release-on-pypi/) (see the "The whole release is bad" header).

Thanks in advance!

**Comment by cpburnz** [comment] 2022-09-05 13:44
@ichard26 I have no problem with pulling down v0.10.0 because it broke a very common pattern.

**Comment by cpburnz** [comment] 2025-06-12 12:57
> git explains in their documentation regarding pattern matching, [that an asterisk "*" matches anything except a slash](https://git-scm.com/docs/gitignore#_pattern_format) which translates to me no subfolder should be matched. I was under the impression that "gitwildmatch" is trying to follow git matching and this seems like a huge diversion to it.

The original intention of "gitwildmatch" was to exactly follow the rules described under "PATTERN FORM". Then over the years after many bug reports about deviations from gitignore behavior, it became apparent that the patterns described on that page have many exceptions, and it doesn't explain all the behaviors of gitignore.

One thing I've been thinking about doing is having two versions of "gitwildmatch". One that matches the behavior of gitignore, and another that's a pure or simplified form that only follows the rules described under "PATTERN FORM".

> How would you then match all files within the current root folder and not within subfolder?

Assume these files and folder exists:

```
root.txt
subdir/sub.txt
subdir/nested/third.txt
```


To match files to ignore like gitignore, you can use the following:

```python
>>> from pathspec import GitIgnoreSpec
>>> spec = GitIgnoreSpec.from_lines(['*', '!/*'])
>>> all_files = {'root.txt', 'subdir/sub.txt', 'subdir/nested/third.txt'}
>>> ignore_files = set(spec.match_files(all_files))
>>> keep_files = all_files - ignore_files
>>> print(ignore_files)
{'subdir/sub.txt', 'subdir/nested/third.txt'}
>>> print(keep_files)
{'root.txt'}
```

Where the patterns are:

- `*` - Match all files which will be ignored
- `!/*` - Except for root files.


If you actually want to just match the files directly using "gitwildmatch", the
patterns will need to be reversed:

```python
>>> from pathspec import PathSpec
>>> spec = PathSpec.from_lines('gitwildmatch', ['*', '!/*/'])
>>> all_files = {'root.txt', 'subdir/sub.txt', 'subdir/nested/third.txt'}
>>> match_files = set(spec.match_files(all_files))
>>> print(match_files)
{'root.txt'}
```

Where the patterns are:

- `*` - Match all files.
- `!/*/` - Except for files in subfolders.

**Comment by b-morgenthaler** [comment] 2025-06-12 13:13
@cpburnz Thank's al lot.  That was very helpful to me
